version: '3'
services:
  app:
    container_name: ${APP_NAME}
    image: ${APP_NAME}
    build: .
    command: ['npm', 'start']
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
